# Generated by Django 2.2.3 on 2019-10-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_id', models.CharField(blank=True, default=None, max_length=100)),
                ('incident_location', models.CharField(default=None, max_length=100)),
                ('first_name', models.CharField(blank=True, default=None, max_length=100)),
                ('gender', models.CharField(blank=True, default=None, max_length=100)),
                ('height', models.CharField(blank=True, default=None, max_length=100)),
                ('hair', models.CharField(blank=True, default=None, max_length=100)),
                ('eye_color', models.CharField(blank=True, default=None, max_length=100)),
                ('ethnicity', models.CharField(blank=True, default=None, max_length=100)),
                ('age', models.CharField(default=None, max_length=100)),
                ('ig_handle', models.CharField(blank=True, default=None, max_length=100)),
                ('fb_url', models.CharField(blank=True, default=None, max_length=100)),
                ('snap_user', models.CharField(blank=True, default=None, max_length=100)),
                ('phone_num', models.CharField(blank=True, default=None, max_length=100)),
                ('organizations', models.CharField(blank=True, default=None, max_length=100)),
            ],
        ),
    ]
