# Generated by Django 2.2.3 on 2019-10-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='age',
        ),
        migrations.RemoveField(
            model_name='report',
            name='ethnicity',
        ),
        migrations.RemoveField(
            model_name='report',
            name='eye_color',
        ),
        migrations.RemoveField(
            model_name='report',
            name='fb_url',
        ),
        migrations.RemoveField(
            model_name='report',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='report',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='report',
            name='hair',
        ),
        migrations.RemoveField(
            model_name='report',
            name='height',
        ),
        migrations.RemoveField(
            model_name='report',
            name='ig_handle',
        ),
        migrations.RemoveField(
            model_name='report',
            name='incident_location',
        ),
        migrations.RemoveField(
            model_name='report',
            name='net_id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='organizations',
        ),
        migrations.RemoveField(
            model_name='report',
            name='phone_num',
        ),
        migrations.RemoveField(
            model_name='report',
            name='snap_user',
        ),
        migrations.AddField(
            model_name='report',
            name='uwnetid',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
