# Generated by Django 2.2.3 on 2019-10-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191013_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
