# Generated by Django 2.2.6 on 2019-10-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191013_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='case_type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
